### ISSUE TITLE
Add to readMe file

### ISSUE THREAD

**Issue by abhijit49** [dlucifer8/HacktoberFest_2022#1]

**Comment by saishubham468** [comment]
Hi @abhijit49,I would like to contribute to this issue.

**Comment by saishubham468** [comment]
@abhijit49 i would like to know what changes should be made.

**Comment by abhijit49** [comment]
@saishubham468 Read the README.md file you will understand how to contribute to this repo

**Comment by saishubham468** [comment]
Hi @abhijit49 i have created a PR #2 . Please do accept it.
